import {
  CAPTION_TRACKS_EVENT,
  type CaptionTrack,
  type CaptionTracksEventDetail,
} from '../../src/platform/youtube/types';

interface YouTubeText {
  runs?: Array<{ text?: string }>;
  simpleText?: string;
}

interface YouTubeCaptionTrack {
  baseUrl?: string;
  kind?: string;
  languageCode?: string;
  name?: YouTubeText;
}

interface YouTubePlayerResponse {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: YouTubeCaptionTrack[];
    };
  };
  videoDetails?: {
    videoId?: string;
  };
}

function textValue(value: YouTubeText | undefined): string {
  return value?.simpleText ?? value?.runs?.map((run) => run.text ?? '').join('') ?? '';
}

function readPlayerResponse(): YouTubePlayerResponse | undefined {
  return (window as typeof window & { ytInitialPlayerResponse?: YouTubePlayerResponse })
    .ytInitialPlayerResponse;
}

function currentVideoId(response: YouTubePlayerResponse | undefined): string {
  if (response?.videoDetails?.videoId) return response.videoDetails.videoId;
  const url = new URL(window.location.href);
  return url.searchParams.get('v') ?? url.pathname.match(/^\/shorts\/([^/]+)/u)?.[1] ?? '';
}

function publishCaptionTracks(): void {
  const response = readPlayerResponse();
  const rawTracks = response?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  const tracks: CaptionTrack[] = rawTracks.flatMap((track) => {
    if (!track.baseUrl || !track.languageCode) return [];
    return [
      {
        baseUrl: track.baseUrl,
        languageCode: track.languageCode,
        name: textValue(track.name) || track.languageCode,
        isAutoGenerated: track.kind === 'asr',
      },
    ];
  });
  const detail: CaptionTracksEventDetail = {
    videoId: currentVideoId(response),
    tracks,
  };

  window.dispatchEvent(new CustomEvent(CAPTION_TRACKS_EVENT, { detail }));
}

export default defineContentScript({
  matches: ['*://www.youtube.com/*'],
  world: 'MAIN',
  runAt: 'document_start',
  main() {
    const publishSoon = () => {
      window.setTimeout(publishCaptionTracks, 0);
      window.setTimeout(publishCaptionTracks, 600);
      window.setTimeout(publishCaptionTracks, 1_500);
    };

    window.addEventListener('yt-navigate-finish', publishSoon);
    window.addEventListener('yt-page-data-updated', publishSoon);
    window.addEventListener('popstate', publishSoon);
    publishSoon();
  },
});
