import {
  addPlaybackContext,
  fetchCaptionTracksViaInnertube,
} from '../../src/platform/youtube/captions';
import { loadPageCaptionTrack, withCaptionTimeout } from '../../src/platform/youtube/track-loader';
import {
  CAPTION_TRACK_REQUEST_EVENT,
  CAPTION_TRACK_RESPONSE_EVENT,
  CAPTION_TRACKS_EVENT,
  CAPTION_TRACKS_REQUEST_EVENT,
  type CaptionTrack,
  type CaptionTrackRequestDetail,
  type CaptionTrackResponseDetail,
  type CaptionTracksEventDetail,
} from '../../src/platform/youtube/types';

interface YouTubeText {
  runs?: Array<{ text?: string }>;
  simpleText?: string;
}

interface YouTubeCaptionTrack {
  baseUrl?: string;
  kind?: string;
  languageCode?: string;
  name?: YouTubeText;
}

interface YouTubePlayerResponse {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: YouTubeCaptionTrack[];
    };
  };
  videoDetails?: {
    videoId?: string;
  };
}

function textValue(value: YouTubeText | undefined): string {
  return value?.simpleText ?? value?.runs?.map((run) => run.text ?? '').join('') ?? '';
}

function readPlayerResponse(): YouTubePlayerResponse | undefined {
  const player = document.querySelector('.html5-video-player') as
    (HTMLElement & { getPlayerResponse?: () => YouTubePlayerResponse }) | null;
  try {
    const live = player?.getPlayerResponse?.();
    if (live?.videoDetails?.videoId === currentVideoId()) return live;
  } catch {
    // The player API is temporarily unavailable during navigation.
  }
  return (window as typeof window & { ytInitialPlayerResponse?: YouTubePlayerResponse })
    .ytInitialPlayerResponse;
}

function currentVideoId(): string {
  const url = new URL(window.location.href);
  return url.searchParams.get('v') ?? url.pathname.match(/^\/shorts\/([^/]+)/u)?.[1] ?? '';
}

function mapCaptionTracks(response: YouTubePlayerResponse | undefined): CaptionTrack[] {
  const rawTracks = response?.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  return rawTracks.flatMap((track) => {
    if (!track.baseUrl || !track.languageCode) return [];
    return [
      {
        baseUrl: track.baseUrl,
        languageCode: track.languageCode,
        name: textValue(track.name) || track.languageCode,
        isAutoGenerated: track.kind === 'asr',
      },
    ];
  });
}

const trackRequests = new Map<string, Promise<CaptionTrack[]>>();

function discoverCaptionTracks(videoId: string, apiKey: string): Promise<CaptionTrack[]> {
  const existing = trackRequests.get(videoId);
  if (existing) return existing;

  const request = withCaptionTimeout((signal) =>
    fetchCaptionTracksViaInnertube({ videoId, apiKey, signal }),
  ).catch(() => {
    trackRequests.delete(videoId);
    return [];
  });
  trackRequests.set(videoId, request);
  if (trackRequests.size > 12) {
    const oldestVideoId = trackRequests.keys().next().value;
    if (oldestVideoId) trackRequests.delete(oldestVideoId);
  }
  return request;
}

async function publishCaptionTracks(): Promise<void> {
  const videoId = currentVideoId();
  if (!videoId) return;

  const response = readPlayerResponse();
  let tracks = response?.videoDetails?.videoId === videoId ? mapCaptionTracks(response) : [];
  if (tracks.length === 0) {
    const apiKey = readInnertubeApiKey();
    if (apiKey) tracks = await discoverCaptionTracks(videoId, apiKey);
  }
  if (currentVideoId() !== videoId) return;
  // A delayed discovery response must not clear tracks found while it was in flight.
  const current = readPlayerResponse();
  const currentTracks = current?.videoDetails?.videoId === videoId ? mapCaptionTracks(current) : [];
  if (currentTracks.length > 0) tracks = currentTracks;
  const detail: CaptionTracksEventDetail = {
    videoId,
    tracks,
  };

  window.dispatchEvent(new CustomEvent(CAPTION_TRACKS_EVENT, { detail }));
}

function parseCaptionTrackRequest(event: Event): CaptionTrackRequestDetail | undefined {
  const value = (event as CustomEvent<unknown>).detail;
  if (typeof value !== 'string') return undefined;

  try {
    const detail = JSON.parse(value) as CaptionTrackRequestDetail;
    const url = new URL(detail.track.baseUrl);
    const isYouTubeCaptionUrl =
      url.protocol === 'https:' &&
      (url.hostname === 'youtube.com' || url.hostname.endsWith('.youtube.com')) &&
      url.pathname === '/api/timedtext';

    return detail.requestId && detail.track.languageCode && isYouTubeCaptionUrl
      ? detail
      : undefined;
  } catch {
    return undefined;
  }
}

function publishCaptionTrackResponse(detail: CaptionTrackResponseDetail): void {
  window.dispatchEvent(
    new CustomEvent(CAPTION_TRACK_RESPONSE_EVENT, { detail: JSON.stringify(detail) }),
  );
}

function findObservedCaptionUrl(track: CaptionTrack): string | undefined {
  const requested = new URL(track.baseUrl);
  const videoId = requested.searchParams.get('v');
  const entries = performance.getEntriesByType('resource').slice().reverse();

  for (const entry of entries) {
    try {
      const observed = new URL(entry.name);
      const isMatchingTrack =
        observed.hostname.endsWith('.youtube.com') &&
        observed.pathname === '/api/timedtext' &&
        observed.searchParams.get('v') === videoId &&
        observed.searchParams.get('lang') === track.languageCode &&
        observed.searchParams.has('pot');
      if (isMatchingTrack) return observed.toString();
    } catch {
      // Ignore non-URL resource entries.
    }
  }

  return undefined;
}

function readInnertubeApiKey(): string | undefined {
  const configured = (
    window as typeof window & { ytcfg?: { get?: (key: string) => unknown } }
  ).ytcfg?.get?.('INNERTUBE_API_KEY');
  if (typeof configured === 'string' && configured.length > 0) return configured;

  for (const script of document.scripts) {
    const match = script.textContent?.match(/"INNERTUBE_API_KEY":"([A-Za-z0-9_-]+)"/u);
    if (match?.[1]) return match[1];
  }

  return undefined;
}

async function respondWithCaptionTrack(detail: CaptionTrackRequestDetail): Promise<void> {
  const apiKey = readInnertubeApiKey();
  try {
    const observedUrl = findObservedCaptionUrl(detail.track);
    const cues = await loadPageCaptionTrack({
      track: detail.track,
      ...(apiKey ? { apiKey } : {}),
      ...(observedUrl ? { observedTrack: addPlaybackContext(detail.track, observedUrl) } : {}),
    });
    publishCaptionTrackResponse({ requestId: detail.requestId, ok: true, cues });
  } catch (error) {
    publishCaptionTrackResponse({
      requestId: detail.requestId,
      ok: false,
      error: error instanceof Error ? error.message : '字幕轨读取失败，请刷新视频后重试。',
    });
  }
}

export default defineContentScript({
  matches: ['*://www.youtube.com/*'],
  world: 'MAIN',
  runAt: 'document_start',
  main() {
    const publishSoon = () => {
      window.setTimeout(() => void publishCaptionTracks(), 0);
      window.setTimeout(() => void publishCaptionTracks(), 600);
      window.setTimeout(() => void publishCaptionTracks(), 1_500);
    };

    window.addEventListener('yt-navigate-finish', publishSoon);
    window.addEventListener('yt-page-data-updated', publishSoon);
    window.addEventListener('popstate', publishSoon);
    window.addEventListener(CAPTION_TRACKS_REQUEST_EVENT, publishSoon);
    window.addEventListener(CAPTION_TRACK_REQUEST_EVENT, (event) => {
      const detail = parseCaptionTrackRequest(event);
      if (detail) void respondWithCaptionTrack(detail);
    });
    publishSoon();
  },
});
