import type { DisplayCue, RawCue, SourceToken, TokenWindow } from '@cueweave/core/subtitle';
import type { ContentState } from '../platform/youtube/types';
import type { BufferWindowState } from '../provider/playbackBuffer';
import type { SubtitlePreferences } from '../settings/subtitle';

export const DEBUG_STORAGE_KEY = 'cueweave.debug';
export const GET_DEBUG_STATE = 'cueweave:get-debug-state';
export const SET_DEBUG_STATE = 'cueweave:set-debug-state';
export const DEBUG_ENABLED_CHANGED = 'cueweave:debug-enabled-changed';
export const RECORD_DEBUG_EVENT = 'cueweave:record-debug-event';
export const CAPTURE_DEBUG_SNAPSHOT = 'cueweave:capture-debug-snapshot';
export const EXPORT_DEBUG_REPORT = 'cueweave:export-debug-report';

export const DEBUG_POLICY = {
  maxAgeMs: 24 * 60 * 60 * 1_000,
  maxBytes: 3 * 1024 * 1024,
  maxRecords: 500,
  maxRecordBytes: 512 * 1024,
  maxResponseBytes: 384 * 1024,
  recentEventMs: 5 * 60 * 1_000,
} as const;

export interface DebugScope {
  videoId: string;
  sessionId?: string;
  tabId?: number;
  windowId?: string;
  startMs?: number;
  endMs?: number;
  operation?: string;
}

export interface DebugRecord {
  id: string;
  buildId?: string;
  time: number;
  updatedAt: number;
  scope: DebugScope;
  kind: string;
  data: unknown;
}

export interface DebugState {
  enabled: boolean;
  enabledAt: number | null;
  generation: string;
  records: DebugRecord[];
  evictedRecords: number;
}

export interface DebugSnapshot {
  capturedAt: number;
  videoId: string;
  sessionId: string;
  contentBuild: string;
  timeMs: number | null;
  videoTitle: string;
  playback: {
    paused: boolean;
    seeking: boolean;
    playbackRate: number;
    durationMs: number | null;
    readyState: number;
  } | null;
  state: ContentState;
  preferences: SubtitlePreferences;
  track: { languageCode: string; name: string; isAutoGenerated: boolean } | null;
  range: { startMs: number; endMs: number } | null;
  windows: Array<TokenWindow & { state?: BufferWindowState }>;
  rawCues: RawCue[];
  sourceTokens: SourceToken[];
  originalCues: DisplayCue[];
  translatedCues: DisplayCue[];
  display: {
    originalText: string;
    translationText: string;
    hidden: boolean;
    playerWidth: number | null;
    playerHeight: number | null;
    fullscreen: boolean;
  };
}

export type DebugExportResult =
  { ok: true; filename: string; json: string; partial: boolean } | { ok: false; message: string };

export function isDebugRecord(value: unknown): value is DebugRecord {
  if (!value || typeof value !== 'object') return false;
  const r = value as DebugRecord;
  return (
    typeof r.id === 'string' &&
    Number.isFinite(r.time) &&
    Number.isFinite(r.updatedAt) &&
    typeof r.kind === 'string' &&
    !!r.scope &&
    typeof r.scope.videoId === 'string'
  );
}
