import { afterEach, describe, expect, it, vi } from 'vitest';
import { addPlaybackContext, fetchCaptionTrack, parseJson3Captions } from './captions';

const track = {
  baseUrl: 'https://www.youtube.com/api/timedtext?v=test&lang=en',
  languageCode: 'en',
  name: 'English',
  isAutoGenerated: true,
};

afterEach(() => {
  vi.unstubAllGlobals();
});

describe('parseJson3Captions', () => {
  it('maps JSON3 events to stable raw cues', () => {
    const cues = parseJson3Captions({
      events: [
        { tStartMs: 100, dDurationMs: 400, segs: [{ utf8: 'Hello ' }, { utf8: 'world' }] },
        { tStartMs: 500, segs: [{ utf8: 'Again' }] },
      ],
    });

    expect(cues).toEqual([
      { id: 'yt:0:100', startMs: 100, endMs: 500, text: 'Hello world' },
      { id: 'yt:1:500', startMs: 500, endMs: 2_500, text: 'Again' },
    ]);
  });

  it('ignores metadata events without caption text', () => {
    expect(parseJson3Captions({ events: [{ tStartMs: 0 }] })).toEqual([]);
  });

  it('requests JSON3 and parses a successful response body', async () => {
    const fetchMock = vi.fn().mockResolvedValue(
      new Response(
        JSON.stringify({
          events: [{ tStartMs: 100, dDurationMs: 400, segs: [{ utf8: 'Hello' }] }],
        }),
      ),
    );
    vi.stubGlobal('fetch', fetchMock);

    await expect(fetchCaptionTrack(track)).resolves.toHaveLength(1);
    expect(fetchMock).toHaveBeenCalledWith(
      expect.objectContaining({ search: expect.stringContaining('fmt=json3') }),
      expect.objectContaining({ credentials: 'include' }),
    );
  });

  it('reports an empty successful response without leaking a JSON parser error', async () => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response('')));

    await expect(fetchCaptionTrack(track)).rejects.toThrow('YouTube 返回了空字幕数据');
  });

  it('reports an invalid response format clearly', async () => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response('<timedtext />')));

    await expect(fetchCaptionTrack(track)).rejects.toThrow('YouTube 返回了无法识别的字幕格式');
  });

  it('adds player-generated proof-of-origin context without changing the selected track', () => {
    const contextualized = addPlaybackContext(
      track,
      'https://www.youtube.com/api/timedtext?v=test&lang=en&tlang=zh-Hans&pot=proof&potc=1&c=WEB',
    );
    const url = new URL(contextualized.baseUrl);

    expect(url.searchParams.get('pot')).toBe('proof');
    expect(url.searchParams.get('potc')).toBe('1');
    expect(url.searchParams.get('c')).toBe('WEB');
    expect(url.searchParams.get('tlang')).toBeNull();
    expect(contextualized.languageCode).toBe('en');
  });
});
