import type { RawCue } from '../../domain/subtitle';
import type { CaptionTrack } from './types';

interface Json3Segment {
  tOffsetMs?: number;
  utf8?: string;
}

interface Json3Event {
  tStartMs?: number;
  dDurationMs?: number;
  segs?: Json3Segment[];
}

interface Json3CaptionPayload {
  events?: Json3Event[];
}

interface InnertubeText {
  runs?: Array<{ text?: string }>;
  simpleText?: string;
}

interface InnertubeCaptionTrack {
  baseUrl?: string;
  kind?: string;
  languageCode?: string;
  name?: InnertubeText;
}

interface InnertubePlayerResponse {
  captions?: {
    playerCaptionsTracklistRenderer?: {
      captionTracks?: InnertubeCaptionTrack[];
    };
  };
}

interface ParsedCaptionEvent {
  startMs: number;
  durationMs: number;
  text: string;
  segments: Json3Segment[];
}

const PLAYBACK_CONTEXT_PARAMS = [
  'pot',
  'potc',
  'c',
  'cver',
  'cplayer',
  'cbr',
  'cbrver',
  'cos',
  'cosver',
  'cplatform',
  'xorb',
  'xobt',
  'xovt',
] as const;

function parseCaptionEvents(payload: Json3CaptionPayload): ParsedCaptionEvent[] {
  return (payload.events ?? [])
    .map((event) => ({
      startMs: event.tStartMs ?? 0,
      durationMs: event.dDurationMs ?? 0,
      text: (event.segs ?? []).map((segment) => segment.utf8 ?? '').join(''),
      segments: event.segs ?? [],
    }))
    .filter((event) => event.text.trim().length > 0);
}

export function parseJson3Captions(payload: Json3CaptionPayload): RawCue[] {
  const events = parseCaptionEvents(payload);

  return events.map((event, index) => {
    const next = events[index + 1];
    const fallbackEndMs = next?.startMs ?? event.startMs + 2_000;
    const endMs = event.durationMs > 0 ? event.startMs + event.durationMs : fallbackEndMs;
    const finalWordEndMs = next ? Math.min(endMs, next.startMs) : endMs;

    const nonEmptySegments = event.segments.filter(
      (segment) => (segment.utf8 ?? '').trim().length > 0,
    );
    const words = nonEmptySegments.map((segment, wordIndex) => {
      const nextSegment = nonEmptySegments[wordIndex + 1];
      const startOffsetMs = segment.tOffsetMs ?? 0;
      const nextOffsetMs = nextSegment?.tOffsetMs;
      const wordStartMs = event.startMs + startOffsetMs;
      const wordEndMs =
        typeof nextOffsetMs === 'number' ? event.startMs + nextOffsetMs : finalWordEndMs;

      return {
        id: `yt:${index}:${event.startMs}:word:${wordIndex}`,
        startMs: wordStartMs,
        endMs: Math.max(wordStartMs + 1, wordEndMs),
        text: segment.utf8?.trim() ?? '',
      };
    });

    return {
      id: `yt:${index}:${event.startMs}`,
      startMs: event.startMs,
      endMs: Math.max(event.startMs + 1, endMs),
      text: event.text,
      ...(words.length > 0 ? { words } : {}),
    };
  });
}

export function addPlaybackContext(track: CaptionTrack, observedCaptionUrl: string): CaptionTrack {
  const target = new URL(track.baseUrl);
  const observed = new URL(observedCaptionUrl);

  for (const key of PLAYBACK_CONTEXT_PARAMS) {
    const value = observed.searchParams.get(key);
    if (value) target.searchParams.set(key, value);
  }

  return { ...track, baseUrl: target.toString() };
}

function innertubeText(value: InnertubeText | undefined): string {
  return value?.simpleText ?? value?.runs?.map((run) => run.text ?? '').join('') ?? '';
}

function selectInnertubeTrack(
  tracks: readonly CaptionTrack[],
  preferredLanguageCode: string,
): CaptionTrack | undefined {
  const matching = tracks.filter((track) => track.languageCode === preferredLanguageCode);
  return matching.find((track) => !track.isAutoGenerated) ?? matching[0] ?? tracks[0];
}

export async function fetchCaptionTracksViaInnertube(options: {
  apiKey: string;
  signal?: AbortSignal;
  videoId: string;
}): Promise<CaptionTrack[]> {
  const response = await fetch(
    `https://www.youtube.com/youtubei/v1/player?key=${encodeURIComponent(options.apiKey)}`,
    {
      method: 'POST',
      credentials: 'omit',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        context: {
          client: {
            clientName: 'ANDROID',
            clientVersion: '20.10.38',
            hl: 'en',
            gl: 'US',
          },
        },
        videoId: options.videoId,
        contentCheckOk: true,
        racyCheckOk: true,
      }),
      ...(options.signal ? { signal: options.signal } : {}),
    },
  );
  if (!response.ok) {
    throw new Error(`YouTube 播放器接口请求失败（HTTP ${response.status}）。`);
  }

  const payload = (await response.json()) as InnertubePlayerResponse;
  const rawTracks = payload.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
  return rawTracks.flatMap((track) =>
    track.baseUrl && track.languageCode
      ? [
          {
            baseUrl: track.baseUrl,
            languageCode: track.languageCode,
            name: innertubeText(track.name) || track.languageCode,
            isAutoGenerated: track.kind === 'asr',
          },
        ]
      : [],
  );
}

export async function fetchCaptionTrackViaInnertube(options: {
  apiKey: string;
  preferredLanguageCode: string;
  signal?: AbortSignal;
  videoId: string;
}): Promise<RawCue[]> {
  const tracks = await fetchCaptionTracksViaInnertube(options);
  const selected = selectInnertubeTrack(tracks, options.preferredLanguageCode);
  if (!selected) {
    throw new Error('YouTube 播放器接口没有返回可用字幕轨。');
  }

  return fetchCaptionTrack(selected, options.signal);
}

export async function fetchCaptionTrack(
  track: CaptionTrack,
  signal?: AbortSignal,
): Promise<RawCue[]> {
  const url = new URL(track.baseUrl);
  url.searchParams.set('fmt', 'json3');

  const response = await fetch(url, {
    credentials: 'include',
    ...(signal ? { signal } : {}),
  });
  if (!response.ok) {
    throw new Error(
      `YouTube subtitle request failed with HTTP ${response.status}. Reload the video and try again.`,
    );
  }

  const body = await response.text();
  if (!body.trim()) {
    throw new Error('YouTube 返回了空字幕数据，请刷新视频页面后重试。');
  }

  let payload: Json3CaptionPayload;
  try {
    payload = JSON.parse(body) as Json3CaptionPayload;
  } catch {
    throw new Error('YouTube 返回了无法识别的字幕格式，请刷新视频页面后重试。');
  }

  const cues = parseJson3Captions(payload);
  if (cues.length === 0) {
    throw new Error('YouTube 字幕轨中没有可显示的文本。');
  }

  return cues;
}
