import { afterEach, describe, expect, it, vi } from 'vitest';
import {
  addPlaybackContext,
  fetchCaptionTrack,
  fetchCaptionTrackViaInnertube,
  parseJson3Captions,
} from './captions';

const track = {
  baseUrl: 'https://www.youtube.com/api/timedtext?v=test&lang=en',
  languageCode: 'en',
  name: 'English',
  isAutoGenerated: true,
};

afterEach(() => {
  vi.unstubAllGlobals();
});

describe('parseJson3Captions', () => {
  it('maps JSON3 events to stable raw cues', () => {
    const cues = parseJson3Captions({
      events: [
        {
          tStartMs: 100,
          dDurationMs: 400,
          segs: [{ utf8: 'Hello ' }, { utf8: 'world', tOffsetMs: 180 }],
        },
        { tStartMs: 500, segs: [{ utf8: 'Again' }] },
      ],
    });

    expect(cues).toEqual([
      {
        id: 'yt:0:100',
        startMs: 100,
        endMs: 500,
        text: 'Hello world',
        words: [
          { id: 'yt:0:100:word:0', startMs: 100, endMs: 280, text: 'Hello' },
          { id: 'yt:0:100:word:1', startMs: 280, endMs: 500, text: 'world' },
        ],
      },
      {
        id: 'yt:1:500',
        startMs: 500,
        endMs: 2_500,
        text: 'Again',
        words: [{ id: 'yt:1:500:word:0', startMs: 500, endMs: 2_500, text: 'Again' }],
      },
    ]);
  });

  it('ignores metadata events without caption text', () => {
    expect(parseJson3Captions({ events: [{ tStartMs: 0 }] })).toEqual([]);
  });

  it('caps the final word at the next text event when ASR event durations overlap', () => {
    const cues = parseJson3Captions({
      events: [
        { tStartMs: 0, dDurationMs: 4_000, segs: [{ utf8: 'First' }] },
        { tStartMs: 2_000, dDurationMs: 2_000, segs: [{ utf8: 'Second' }] },
      ],
    });

    expect(cues[0]?.endMs).toBe(4_000);
    expect(cues[0]?.words?.[0]?.endMs).toBe(2_000);
    expect(cues[1]?.words?.[0]?.startMs).toBe(2_000);
  });

  it('requests JSON3 and parses a successful response body', async () => {
    const fetchMock = vi.fn().mockResolvedValue(
      new Response(
        JSON.stringify({
          events: [{ tStartMs: 100, dDurationMs: 400, segs: [{ utf8: 'Hello' }] }],
        }),
      ),
    );
    vi.stubGlobal('fetch', fetchMock);

    await expect(fetchCaptionTrack(track)).resolves.toHaveLength(1);
    expect(fetchMock).toHaveBeenCalledWith(
      expect.objectContaining({ search: expect.stringContaining('fmt=json3') }),
      expect.objectContaining({ credentials: 'include' }),
    );
  });

  it('reports an empty successful response without leaking a JSON parser error', async () => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response('')));

    await expect(fetchCaptionTrack(track)).rejects.toThrow('YouTube 返回了空字幕数据');
  });

  it('reports an invalid response format clearly', async () => {
    vi.stubGlobal('fetch', vi.fn().mockResolvedValue(new Response('<timedtext />')));

    await expect(fetchCaptionTrack(track)).rejects.toThrow('YouTube 返回了无法识别的字幕格式');
  });

  it('adds player-generated proof-of-origin context without changing the selected track', () => {
    const contextualized = addPlaybackContext(
      track,
      'https://www.youtube.com/api/timedtext?v=test&lang=en&tlang=zh-Hans&pot=proof&potc=1&c=WEB',
    );
    const url = new URL(contextualized.baseUrl);

    expect(url.searchParams.get('pot')).toBe('proof');
    expect(url.searchParams.get('potc')).toBe('1');
    expect(url.searchParams.get('c')).toBe('WEB');
    expect(url.searchParams.get('tlang')).toBeNull();
    expect(contextualized.languageCode).toBe('en');
  });

  it('loads an independent caption track through the Android Innertube client', async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce(
        new Response(
          JSON.stringify({
            captions: {
              playerCaptionsTracklistRenderer: {
                captionTracks: [
                  {
                    baseUrl: track.baseUrl,
                    languageCode: 'en',
                    kind: 'asr',
                    name: { simpleText: 'English' },
                  },
                ],
              },
            },
          }),
        ),
      )
      .mockResolvedValueOnce(
        new Response(
          JSON.stringify({
            events: [{ tStartMs: 100, dDurationMs: 400, segs: [{ utf8: 'Independent' }] }],
          }),
        ),
      );
    vi.stubGlobal('fetch', fetchMock);

    const cues = await fetchCaptionTrackViaInnertube({
      videoId: 'test',
      apiKey: 'public-page-key',
      preferredLanguageCode: 'en',
    });

    expect(cues[0]?.text).toBe('Independent');
    expect(fetchMock).toHaveBeenNthCalledWith(
      1,
      expect.stringContaining('/youtubei/v1/player?key=public-page-key'),
      expect.objectContaining({ method: 'POST', credentials: 'omit' }),
    );
  });
});
