import type { RawCue } from '../../domain/subtitle';

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface CaptionTracksEventDetail {
  videoId: string;
  tracks: CaptionTrack[];
}

export interface CaptionTrackRequestDetail {
  requestId: string;
  track: CaptionTrack;
}

export type CaptionTrackResponseDetail =
  | {
      requestId: string;
      ok: true;
      cues: RawCue[];
    }
  | {
      requestId: string;
      ok: false;
      error: string;
    };

export type ContentStatus = 'idle' | 'loading' | 'ready' | 'no-captions' | 'error';

export interface ContentState {
  status: ContentStatus;
  enabled: boolean;
  videoId?: string | undefined;
  languageCode?: string | undefined;
  cueCount: number;
  segmentCount: number;
  message?: string | undefined;
}

export const CAPTION_TRACKS_EVENT = 'cueweave:caption-tracks';
export const CAPTION_TRACK_REQUEST_EVENT = 'cueweave:caption-track-request';
export const CAPTION_TRACK_RESPONSE_EVENT = 'cueweave:caption-track-response';
export const GET_CONTENT_STATE_MESSAGE = 'cueweave:get-content-state';
