export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface CaptionTracksEventDetail {
  videoId: string;
  tracks: CaptionTrack[];
}

export type ContentStatus = 'idle' | 'loading' | 'ready' | 'no-captions' | 'error';

export interface ContentState {
  status: ContentStatus;
  enabled: boolean;
  videoId?: string | undefined;
  languageCode?: string | undefined;
  cueCount: number;
  segmentCount: number;
  message?: string | undefined;
}

export const CAPTION_TRACKS_EVENT = 'cueweave:caption-tracks';
export const GET_CONTENT_STATE_MESSAGE = 'cueweave:get-content-state';
