import { processSubtitleCues, type SemanticSegment } from '../../src/domain/subtitle';
import { fetchCaptionTrack } from '../../src/platform/youtube/captions';
import {
  CAPTION_TRACKS_EVENT,
  GET_CONTENT_STATE_MESSAGE,
  type CaptionTrack,
  type CaptionTracksEventDetail,
  type ContentState,
} from '../../src/platform/youtube/types';

const ENABLED_KEY = 'cueweave.enabled';
const OVERLAY_ID = 'cueweave-subtitle-overlay';

let state: ContentState = {
  status: 'idle',
  enabled: true,
  cueCount: 0,
  segmentCount: 0,
};
let segments: SemanticSegment[] = [];
let overlayText: HTMLDivElement | undefined;
let activeRequest: AbortController | undefined;
let loadedTrackKey = '';

function updateState(patch: Partial<ContentState>): void {
  state = { ...state, ...patch };
}

function ensureOverlay(): HTMLDivElement | undefined {
  if (overlayText?.isConnected) return overlayText;
  const player = document.querySelector<HTMLElement>('.html5-video-player');
  if (!player) return undefined;

  document.getElementById(OVERLAY_ID)?.remove();
  const host = document.createElement('div');
  host.id = OVERLAY_ID;
  host.setAttribute('aria-hidden', 'true');
  host.style.cssText = [
    'position:absolute',
    'inset:0',
    'pointer-events:none',
    'z-index:60',
    'display:flex',
    'align-items:flex-end',
    'justify-content:center',
    'padding:0 5% 9%',
    'box-sizing:border-box',
  ].join(';');
  const shadow = host.attachShadow({ mode: 'closed' });
  const style = document.createElement('style');
  style.textContent = `
    .cueweave-caption {
      display: none;
      max-width: min(920px, 92%);
      color: #f7efe3;
      background: color-mix(in srgb, #181613 84%, transparent);
      border: 1px solid color-mix(in srgb, #f2a33a 42%, transparent);
      border-radius: 3px;
      box-shadow: 0 8px 32px rgb(0 0 0 / 32%);
      padding: 0.48em 0.75em 0.52em;
      font-family: "Noto Sans CJK SC", "Microsoft YaHei", "PingFang SC", sans-serif;
      font-size: clamp(18px, 2.25vw, 34px);
      font-weight: 600;
      line-height: 1.35;
      text-align: center;
      text-wrap: balance;
      text-shadow: 0 2px 3px rgb(0 0 0 / 72%);
    }
    .cueweave-caption[data-visible="true"] { display: block; }
  `;
  overlayText = document.createElement('div');
  overlayText.className = 'cueweave-caption';
  overlayText.dataset.visible = 'false';
  shadow.append(style, overlayText);
  player.append(host);
  return overlayText;
}

function currentSegmentAt(timeMs: number): SemanticSegment | undefined {
  let low = 0;
  let high = segments.length - 1;

  while (low <= high) {
    const middle = Math.floor((low + high) / 2);
    const segment = segments[middle];
    if (!segment) break;
    if (timeMs < segment.startMs) high = middle - 1;
    else if (timeMs > segment.endMs) low = middle + 1;
    else return segment;
  }

  return undefined;
}

function renderLoop(): void {
  const target = ensureOverlay();
  const video = document.querySelector<HTMLVideoElement>('video.html5-main-video');
  const segment = state.enabled && video ? currentSegmentAt(video.currentTime * 1_000) : undefined;
  const text = segment?.sourceText ?? '';

  if (target) {
    if (target.textContent !== text) target.textContent = text;
    target.dataset.visible = text ? 'true' : 'false';
  }

  window.requestAnimationFrame(renderLoop);
}

function preferredTrack(tracks: readonly CaptionTrack[]): CaptionTrack | undefined {
  return tracks.find((track) => !track.isAutoGenerated) ?? tracks[0];
}

async function loadTrack(detail: CaptionTracksEventDetail): Promise<void> {
  const track = preferredTrack(detail.tracks);
  if (!track) {
    loadedTrackKey = '';
    segments = [];
    updateState({
      status: detail.videoId ? 'no-captions' : 'idle',
      videoId: detail.videoId || undefined,
      languageCode: undefined,
      cueCount: 0,
      segmentCount: 0,
      message: detail.videoId ? '当前视频没有可用字幕。' : undefined,
    });
    return;
  }

  const trackKey = `${detail.videoId}:${track.languageCode}:${track.baseUrl}`;
  if (trackKey === loadedTrackKey) return;
  loadedTrackKey = trackKey;
  activeRequest?.abort();
  activeRequest = new AbortController();
  segments = [];
  updateState({
    status: 'loading',
    videoId: detail.videoId,
    languageCode: track.languageCode,
    cueCount: 0,
    segmentCount: 0,
    message: '正在读取字幕轨。',
  });

  try {
    const cues = await fetchCaptionTrack(track, activeRequest.signal);
    if (activeRequest.signal.aborted || trackKey !== loadedTrackKey) return;
    segments = processSubtitleCues(cues);
    updateState({
      status: 'ready',
      cueCount: cues.length,
      segmentCount: segments.length,
      message: `已载入 ${segments.length} 个完整语义段。`,
    });
  } catch (error) {
    if (activeRequest.signal.aborted || trackKey !== loadedTrackKey) return;
    segments = [];
    updateState({
      status: 'error',
      cueCount: 0,
      segmentCount: 0,
      message: error instanceof Error ? error.message : '字幕轨读取失败，请刷新视频后重试。',
    });
  }
}

export default defineContentScript({
  matches: ['*://www.youtube.com/*'],
  runAt: 'document_start',
  async main() {
    const stored = await browser.storage.local.get([ENABLED_KEY]);
    updateState({ enabled: stored[ENABLED_KEY] !== false });

    browser.storage.onChanged.addListener((changes, areaName) => {
      if (areaName !== 'local' || !changes[ENABLED_KEY]) return;
      updateState({ enabled: changes[ENABLED_KEY].newValue !== false });
    });

    browser.runtime.onMessage.addListener((message: unknown) => {
      if (
        typeof message === 'object' &&
        message !== null &&
        'type' in message &&
        message.type === GET_CONTENT_STATE_MESSAGE
      ) {
        return Promise.resolve(state);
      }
      return undefined;
    });

    window.addEventListener(CAPTION_TRACKS_EVENT, (event) => {
      const detail = (event as CustomEvent<CaptionTracksEventDetail>).detail;
      if (detail && Array.isArray(detail.tracks)) void loadTrack(detail);
    });

    window.requestAnimationFrame(renderLoop);
  },
});
