import { processSubtitleCues, type RawCue, type SemanticSegment } from '../../src/domain/subtitle';
import {
  CAPTION_TRACK_REQUEST_EVENT,
  CAPTION_TRACK_RESPONSE_EVENT,
  CAPTION_TRACKS_EVENT,
  GET_CONTENT_STATE_MESSAGE,
  type CaptionTrack,
  type CaptionTrackRequestDetail,
  type CaptionTrackResponseDetail,
  type CaptionTracksEventDetail,
  type ContentState,
} from '../../src/platform/youtube/types';

const ENABLED_KEY = 'cueweave.enabled';
const OVERLAY_ID = 'cueweave-subtitle-overlay';

let state: ContentState = {
  status: 'idle',
  enabled: true,
  cueCount: 0,
  segmentCount: 0,
};
let segments: SemanticSegment[] = [];
let overlayText: HTMLDivElement | undefined;
let activeRequest: AbortController | undefined;
let loadedTrackKey = '';

function updateState(patch: Partial<ContentState>): void {
  state = { ...state, ...patch };
  const host = document.getElementById(OVERLAY_ID);
  if (host) reflectState(host);
}

function reflectState(host: HTMLElement): void {
  host.dataset.cueweaveStatus = state.status;
  host.dataset.cueweaveCueCount = String(state.cueCount);
  host.dataset.cueweaveSegmentCount = String(state.segmentCount);
  host.dataset.cueweaveMessage = state.message ?? '';
}

function ensureOverlay(): HTMLDivElement | undefined {
  if (overlayText?.isConnected) return overlayText;
  const player = document.querySelector<HTMLElement>('.html5-video-player');
  if (!player) return undefined;

  document.getElementById(OVERLAY_ID)?.remove();
  const host = document.createElement('div');
  host.id = OVERLAY_ID;
  host.setAttribute('aria-hidden', 'true');
  host.style.cssText = [
    'position:absolute',
    'inset:0',
    'pointer-events:none',
    'z-index:60',
    'display:flex',
    'align-items:flex-end',
    'justify-content:center',
    'padding:0 5% 9%',
    'box-sizing:border-box',
  ].join(';');
  reflectState(host);
  const shadow = host.attachShadow({ mode: 'closed' });
  const style = document.createElement('style');
  const regularFontUrl = browser.runtime.getURL('/fonts/MiSans-Regular.woff2');
  const semiboldFontUrl = browser.runtime.getURL('/fonts/MiSans-Semibold.woff2');
  style.textContent = `
    @font-face {
      font-family: "MiSans";
      src: url("${regularFontUrl}") format("woff2");
      font-style: normal;
      font-weight: 400;
      font-display: swap;
    }
    @font-face {
      font-family: "MiSans";
      src: url("${semiboldFontUrl}") format("woff2");
      font-style: normal;
      font-weight: 600;
      font-display: swap;
    }
    :host { font-size: medium; }
    .cueweave-caption {
      display: none;
      max-width: min(52em, 88%);
      color: #f7efe3;
      background: color-mix(in srgb, #181613 84%, transparent);
      border: 1px solid color-mix(in srgb, #f2a33a 42%, transparent);
      border-radius: 3px;
      box-shadow: 0 8px 32px rgb(0 0 0 / 32%);
      padding: 0.48em 0.75em 0.52em;
      font-family: "MiSans", "Mi Sans", "PingFang SC", "Microsoft YaHei", system-ui, sans-serif;
      font-size: clamp(1.125em, 1.65vw, 1.75em);
      font-weight: 600;
      line-height: 1.42;
      text-align: center;
      text-wrap: balance;
      text-shadow: 0 2px 3px rgb(0 0 0 / 72%);
    }
    .cueweave-caption[data-visible="true"] { display: block; }
  `;
  overlayText = document.createElement('div');
  overlayText.className = 'cueweave-caption';
  overlayText.dataset.visible = 'false';
  shadow.append(style, overlayText);
  player.append(host);
  return overlayText;
}

function currentSegmentAt(timeMs: number): SemanticSegment | undefined {
  let low = 0;
  let high = segments.length - 1;

  while (low <= high) {
    const middle = Math.floor((low + high) / 2);
    const segment = segments[middle];
    if (!segment) break;
    if (timeMs < segment.startMs) high = middle - 1;
    else if (timeMs > segment.endMs) low = middle + 1;
    else return segment;
  }

  return undefined;
}

function renderLoop(): void {
  const target = ensureOverlay();
  const video = document.querySelector<HTMLVideoElement>('video.html5-main-video');
  const segment = state.enabled && video ? currentSegmentAt(video.currentTime * 1_000) : undefined;
  const text = segment?.sourceText ?? '';

  if (target) {
    if (target.textContent !== text) target.textContent = text;
    target.dataset.visible = text ? 'true' : 'false';
  }

  window.requestAnimationFrame(renderLoop);
}

function preferredTrack(tracks: readonly CaptionTrack[]): CaptionTrack | undefined {
  return tracks.find((track) => !track.isAutoGenerated) ?? tracks[0];
}

function requestCaptionTrack(track: CaptionTrack, signal: AbortSignal): Promise<RawCue[]> {
  return new Promise((resolve, reject) => {
    const requestId = crypto.randomUUID();
    const request: CaptionTrackRequestDetail = { requestId, track };
    const cleanup = () => {
      window.clearTimeout(timeoutId);
      signal.removeEventListener('abort', handleAbort);
      window.removeEventListener(CAPTION_TRACK_RESPONSE_EVENT, handleResponse);
    };
    const handleAbort = () => {
      cleanup();
      reject(new DOMException('Caption request aborted.', 'AbortError'));
    };
    const handleResponse = (event: Event) => {
      const value = (event as CustomEvent<unknown>).detail;
      if (typeof value !== 'string') return;

      let response: CaptionTrackResponseDetail;
      try {
        response = JSON.parse(value) as CaptionTrackResponseDetail;
      } catch {
        return;
      }
      if (response.requestId !== requestId) return;

      cleanup();
      if (response.ok) resolve(response.cues);
      else reject(new Error(response.error));
    };
    const timeoutId = window.setTimeout(() => {
      cleanup();
      reject(new Error('YouTube 字幕请求超时，请刷新视频页面后重试。'));
    }, 15_000);

    signal.addEventListener('abort', handleAbort, { once: true });
    window.addEventListener(CAPTION_TRACK_RESPONSE_EVENT, handleResponse);
    window.dispatchEvent(
      new CustomEvent(CAPTION_TRACK_REQUEST_EVENT, { detail: JSON.stringify(request) }),
    );
  });
}

async function loadTrack(detail: CaptionTracksEventDetail): Promise<void> {
  const track = preferredTrack(detail.tracks);
  if (!track) {
    loadedTrackKey = '';
    segments = [];
    updateState({
      status: detail.videoId ? 'no-captions' : 'idle',
      videoId: detail.videoId || undefined,
      languageCode: undefined,
      cueCount: 0,
      segmentCount: 0,
      message: detail.videoId ? '当前视频没有可用字幕。' : undefined,
    });
    return;
  }

  const trackKey = `${detail.videoId}:${track.languageCode}:${track.baseUrl}`;
  if (trackKey === loadedTrackKey) return;
  loadedTrackKey = trackKey;
  activeRequest?.abort();
  activeRequest = new AbortController();
  segments = [];
  updateState({
    status: 'loading',
    videoId: detail.videoId,
    languageCode: track.languageCode,
    cueCount: 0,
    segmentCount: 0,
    message: '正在读取字幕轨。',
  });

  try {
    const cues = await requestCaptionTrack(track, activeRequest.signal);
    if (activeRequest.signal.aborted || trackKey !== loadedTrackKey) return;
    segments = processSubtitleCues(cues);
    updateState({
      status: 'ready',
      cueCount: cues.length,
      segmentCount: segments.length,
      message: `已载入 ${segments.length} 个完整语义段。`,
    });
  } catch (error) {
    if (activeRequest.signal.aborted || trackKey !== loadedTrackKey) return;
    segments = [];
    updateState({
      status: 'error',
      cueCount: 0,
      segmentCount: 0,
      message: error instanceof Error ? error.message : '字幕轨读取失败，请刷新视频后重试。',
    });
  }
}

export default defineContentScript({
  matches: ['*://www.youtube.com/*'],
  runAt: 'document_start',
  async main() {
    const stored = await browser.storage.local.get([ENABLED_KEY]);
    updateState({ enabled: stored[ENABLED_KEY] !== false });

    browser.storage.onChanged.addListener((changes, areaName) => {
      if (areaName !== 'local' || !changes[ENABLED_KEY]) return;
      updateState({ enabled: changes[ENABLED_KEY].newValue !== false });
    });

    browser.runtime.onMessage.addListener((message: unknown) => {
      if (
        typeof message === 'object' &&
        message !== null &&
        'type' in message &&
        message.type === GET_CONTENT_STATE_MESSAGE
      ) {
        return Promise.resolve(state);
      }
      return undefined;
    });

    window.addEventListener(CAPTION_TRACKS_EVENT, (event) => {
      const detail = (event as CustomEvent<CaptionTracksEventDetail>).detail;
      if (detail && Array.isArray(detail.tracks)) void loadTrack(detail);
    });

    window.requestAnimationFrame(renderLoop);
  },
});
