import { describe, expect, it } from 'vitest';
import {
  mapCaptionTracks,
  preferredCaptionTrack,
  type YouTubeCaptionTrackList,
} from './track-selection';

const renderer: YouTubeCaptionTrackList = {
  captionTracks: ['ru', 'bn', 'ja', 'en'].map((languageCode) => ({
    baseUrl: `https://www.youtube.com/api/timedtext?v=video&kind=asr&lang=${languageCode}`,
    languageCode,
    kind: 'asr',
    vssId: `a.${languageCode}`,
  })),
  audioTracks: Array.from({ length: 4 }, () => ({ defaultCaptionTrackIndex: 3 })),
};

describe('YouTube caption selection', () => {
  it('uses the declared English source instead of the first dubbed ASR track', () => {
    expect(preferredCaptionTrack(mapCaptionTracks(renderer))?.languageCode).toBe('en');
  });

  it('follows the native caption selection ahead of the default or a manual track', () => {
    const tracks = mapCaptionTracks(renderer, { languageCode: 'ja', kind: 'asr', vss_id: 'a.ja' });
    tracks.unshift({
      baseUrl: 'manual',
      languageCode: 'ru',
      name: 'Russian',
      isAutoGenerated: false,
    });
    expect(preferredCaptionTrack(tracks)?.languageCode).toBe('ja');
  });

  it('uses the default audio track when different audio tracks declare different captions', () => {
    expect(
      preferredCaptionTrack(
        mapCaptionTracks({
          ...renderer,
          audioTracks: [{ defaultCaptionTrackIndex: 0 }, { defaultCaptionTrackIndex: 3 }],
          defaultAudioTrackIndex: 1,
        }),
      )?.languageCode,
    ).toBe('en');
  });

  it('preserves original indices when invalid tracks are filtered out', () => {
    const tracks = mapCaptionTracks({
      ...renderer,
      captionTracks: [{}, ...renderer.captionTracks!.slice(1)],
    });
    expect(preferredCaptionTrack(tracks)?.languageCode).toBe('en');
  });

  it('does not guess English when no preference exists', () => {
    const tracks = mapCaptionTracks({ captionTracks: renderer.captionTracks! });
    expect(preferredCaptionTrack(tracks)?.languageCode).toBe('ru');
    expect(preferredCaptionTrack([])).toBeUndefined();
  });
});
