import type { CaptionTrack } from './types';

export interface YouTubeCaptionTrackList {
  captionTracks?: Array<{
    baseUrl?: string;
    languageCode?: string;
    kind?: string;
    vssId?: string;
    name?: { simpleText?: string; runs?: Array<{ text?: string }> };
  }>;
  defaultAudioTrackIndex?: number;
  audioTracks?: Array<{ defaultCaptionTrackIndex?: number }>;
}

export interface PlayerCaptionSelection {
  languageCode?: string;
  kind?: string;
  vss_id?: string;
}

export function mapCaptionTracks(
  renderer: YouTubeCaptionTrackList | undefined,
  selected?: PlayerCaptionSelection,
): CaptionTrack[] {
  const audioTracks = renderer?.audioTracks ?? [];
  const defaults = audioTracks.map((audio) => audio.defaultCaptionTrackIndex);
  // Some multi-audio videos omit defaultAudioTrackIndex but agree on the source caption.
  const defaultIndex =
    renderer?.defaultAudioTrackIndex !== undefined
      ? audioTracks[renderer.defaultAudioTrackIndex]?.defaultCaptionTrackIndex
      : defaults.length > 0 && defaults.every((index) => index === defaults[0])
        ? defaults[0]
        : undefined;
  return (renderer?.captionTracks ?? []).flatMap((track, index) => {
    if (!track.baseUrl || !track.languageCode) return [];
    const isSelected =
      selected?.vss_id && track.vssId
        ? selected.vss_id === track.vssId
        : Boolean(
            selected?.languageCode === track.languageCode &&
            (selected.kind ?? '') === (track.kind ?? ''),
          );
    return [
      {
        baseUrl: track.baseUrl,
        languageCode: track.languageCode,
        name:
          track.name?.simpleText ??
          track.name?.runs?.map((run) => run.text ?? '').join('') ??
          track.languageCode,
        isAutoGenerated: track.kind === 'asr',
        ...(index === defaultIndex ? { isDefault: true } : {}),
        ...(isSelected ? { isSelected: true } : {}),
      },
    ];
  });
}

export function preferredCaptionTrack(tracks: readonly CaptionTrack[]): CaptionTrack | undefined {
  return (
    tracks.find((track) => track.isSelected) ??
    tracks.find((track) => track.isDefault) ??
    tracks.find((track) => !track.isAutoGenerated) ??
    tracks[0]
  );
}
