import { afterEach, describe, expect, it, vi } from 'vitest';
import {
  CAPTION_ATTEMPT_TIMEOUT_MS,
  loadPageCaptionTrack,
  withCaptionTimeout,
} from './track-loader';

const track = {
  baseUrl: 'https://www.youtube.com/api/timedtext?v=video&lang=en',
  languageCode: 'en',
  name: 'English',
  isAutoGenerated: true,
};
const captionBody = JSON.stringify({
  events: [{ tStartMs: 0, dDurationMs: 1_000, segs: [{ utf8: 'Hello world.' }] }],
});

afterEach(() => {
  vi.unstubAllGlobals();
  vi.useRealTimers();
});

describe('page caption loading', () => {
  it('reads the page track without waiting for or calling the fallback player endpoint', async () => {
    const fetchMock = vi.fn().mockResolvedValue(new Response(captionBody));
    vi.stubGlobal('fetch', fetchMock);
    const cues = await loadPageCaptionTrack({ track, apiKey: 'page-key' });
    expect(cues[0]?.text).toBe('Hello world.');
    expect(fetchMock).toHaveBeenCalledTimes(1);
    expect(String(fetchMock.mock.calls[0]?.[0])).toContain('/api/timedtext');
  });

  it('uses player-observed context when available', async () => {
    const fetchMock = vi.fn().mockResolvedValue(new Response(captionBody));
    vi.stubGlobal('fetch', fetchMock);
    await loadPageCaptionTrack({
      track,
      observedTrack: { ...track, baseUrl: `${track.baseUrl}&pot=observed` },
    });
    expect(String(fetchMock.mock.calls[0]?.[0])).toContain('pot=observed');
  });

  it('can recover through the existing fallback after the page track fails', async () => {
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce(new Response(''))
      .mockResolvedValueOnce(
        new Response(
          JSON.stringify({
            captions: {
              playerCaptionsTracklistRenderer: { captionTracks: [track] },
            },
          }),
        ),
      )
      .mockResolvedValueOnce(new Response(captionBody));
    vi.stubGlobal('fetch', fetchMock);
    await expect(loadPageCaptionTrack({ track, apiKey: 'page-key' })).resolves.toHaveLength(1);
    expect(fetchMock).toHaveBeenCalledTimes(3);
  });

  it('aborts a hung fetch and settles even if the fetch ignores cancellation', async () => {
    vi.useFakeTimers();
    let signal: AbortSignal | undefined;
    const result = withCaptionTimeout((value) => {
      signal = value;
      return new Promise(() => {});
    });
    const assertion = expect(result).rejects.toThrow('字幕请求超时');
    await vi.advanceTimersByTimeAsync(CAPTION_ATTEMPT_TIMEOUT_MS);
    await assertion;
    expect(signal?.aborted).toBe(true);
    expect(vi.getTimerCount()).toBe(0);
  });

  it('bounds a stalled fallback and returns the page-track error rather than remaining loading', async () => {
    vi.useFakeTimers();
    const fetchMock = vi
      .fn()
      .mockResolvedValueOnce(new Response(''))
      .mockImplementationOnce(() => new Promise(() => {}));
    vi.stubGlobal('fetch', fetchMock);
    const assertion = expect(loadPageCaptionTrack({ track, apiKey: 'page-key' })).rejects.toThrow(
      'YouTube 返回了空字幕数据',
    );
    await vi.advanceTimersByTimeAsync(CAPTION_ATTEMPT_TIMEOUT_MS);
    await assertion;
  });

  it('includes a stalled response body in the deadline', async () => {
    vi.useFakeTimers();
    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue({ ok: true, text: () => new Promise(() => {}) }),
    );
    const assertion = expect(loadPageCaptionTrack({ track })).rejects.toThrow('字幕请求超时');
    await vi.advanceTimersByTimeAsync(CAPTION_ATTEMPT_TIMEOUT_MS);
    await assertion;
  });
});
