import type {
  DisplayCue,
  RawCue,
  TranscriptCorrection,
  TranslationTerm,
} from '@cueweave/core/subtitle';
import type { SubtitleDisplayMode, SubtitlePreferences } from '../../settings/subtitle';

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  isAutoGenerated: boolean;
}

export interface CaptionTracksEventDetail {
  videoId: string;
  tracks: CaptionTrack[];
}

export interface CaptionTrackRequestDetail {
  requestId: string;
  track: CaptionTrack;
}

export type CaptionTrackResponseDetail =
  | {
      requestId: string;
      ok: true;
      cues: RawCue[];
    }
  | {
      requestId: string;
      ok: false;
      error: string;
    };

export type ContentStatus = 'idle' | 'loading' | 'ready' | 'no-captions' | 'error';
export type AiStatus = 'idle' | 'working' | 'ready' | 'unconfigured' | 'error';

export interface ContentState {
  status: ContentStatus;
  enabled: boolean;
  videoId?: string | undefined;
  languageCode?: string | undefined;
  cueCount: number;
  displayCueCount: number;
  displayMode: SubtitleDisplayMode;
  aiStatus: AiStatus;
  aiMessage?: string | undefined;
  bufferedSeconds?: number | undefined;
  bufferTargetSeconds?: number | undefined;
  bufferedUntilMs?: number | undefined;
  message?: string | undefined;
  correctionCount?: number | undefined;
  translatedWindowCount?: number | undefined;
  totalWindowCount?: number | undefined;
  fullTranslationStatus?: 'idle' | 'working' | 'ready' | 'error' | undefined;
}

export interface TranscriptReport {
  videoId: string;
  videoTitle: string;
  languageCode?: string;
  originalCues: DisplayCue[];
  translatedCues: DisplayCue[];
  corrections: TranscriptCorrection[];
  terminology: TranslationTerm[];
  translatedWindowCount: number;
  totalWindowCount: number;
  translationComplete: boolean;
  fullTranslationStatus: 'idle' | 'working' | 'ready' | 'error';
  message?: string;
}

export const CAPTION_TRACKS_EVENT = 'cueweave:caption-tracks';
export const CAPTION_TRACKS_REQUEST_EVENT = 'cueweave:request-caption-tracks';
export const CAPTION_TRACK_REQUEST_EVENT = 'cueweave:caption-track-request';
export const CAPTION_TRACK_RESPONSE_EVENT = 'cueweave:caption-track-response';
export const GET_CONTENT_STATE_MESSAGE = 'cueweave:get-content-state';
export const GET_CONTENT_SETTINGS_MESSAGE = 'cueweave:get-content-settings';
export const SET_CONTENT_ENABLED_MESSAGE = 'cueweave:set-content-enabled';
export const SET_SUBTITLE_PREFERENCES_MESSAGE = 'cueweave:set-subtitle-preferences';
export const UPDATE_SUBTITLE_PREFERENCES_MESSAGE = 'cueweave:update-subtitle-preferences';
export const UPDATE_SUBTITLE_DISPLAY_MODE_MESSAGE = 'cueweave:update-subtitle-display-mode';
export const GET_TRANSCRIPT_REPORT_MESSAGE = 'cueweave:get-transcript-report';
export const START_FULL_TRANSLATION_MESSAGE = 'cueweave:start-full-translation';
export const REFRESH_VIDEO_TRANSLATIONS_MESSAGE = 'cueweave:refresh-video-translations';

export interface ContentSettings {
  enabled: boolean;
  subtitlePreferences: SubtitlePreferences;
  debugEnabled?: boolean;
}
